# Generated by Django 3.2 on 2021-04-23 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('makh', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tenkh', models.CharField(max_length=100)),
                ('cmnd', models.CharField(max_length=100)),
                ('sdt', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('ma_khoa', models.ForeignKey(db_column='ma_khoa', on_delete=django.db.models.deletion.CASCADE, to='course.khoatap')),
            ],
            options={
                'db_table': 'khach_hang',
            },
        ),
    ]
