# Generated by Django 3.2 on 2021-04-23 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('ma_loai_san_pham', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tenloai', models.CharField(default='', max_length=100)),
                ('trang_thai', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'loai_san_pham',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('ma_nha_san_xuat', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tennsx', models.CharField(default='', max_length=100)),
                ('sdt', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'nha_san_xuat',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('masp', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tensp', models.CharField(default='', max_length=100)),
                ('chi_tiet_sp', models.TextField(default='')),
                ('xuat_xu', models.CharField(max_length=100)),
                ('hinh', models.ImageField(upload_to='product_imgs/')),
                ('nam_san_xuat', models.DateField()),
                ('gia', models.IntegerField(default=0, null=True)),
                ('dvt', models.CharField(default='VND', max_length=5)),
                ('ma_loai_san_pham', models.ForeignKey(db_column='ma_loai_san_pham', on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('ma_nha_san_xuat', models.ForeignKey(db_column='ma_nha_san_xuat', on_delete=django.db.models.deletion.CASCADE, to='product.manufacturer')),
            ],
            options={
                'db_table': 'san_pham',
            },
        ),
    ]
