# Generated by Django 3.1.7 on 2021-04-28 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loai_tin_tuc',
            fields=[
                ('ma_loai_tin', models.AutoField(primary_key=True, serialize=False)),
                ('ten_loai', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'loai_tin_tuc',
            },
        ),
        migrations.CreateModel(
            name='tin_tuc',
            fields=[
                ('matin', models.AutoField(primary_key=True, serialize=False)),
                ('tieu_de', models.CharField(max_length=100)),
                ('noi_dung', models.TextField()),
                ('ngaydang', models.DateField()),
                ('ma_loai_tin_tuc', models.ForeignKey(db_column='ma_loai_tin', on_delete=django.db.models.deletion.CASCADE, to='tintuc.loai_tin_tuc')),
            ],
            options={
                'db_table': 'tin_tuc',
            },
        ),
    ]
