# Generated by Django 3.1.7 on 2021-05-05 17:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_product_discount'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('madh', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ngay_lap_hoa_don', models.DateField(default=datetime.datetime.today)),
                ('email', models.EmailField(max_length=254)),
                ('dia_chi', models.CharField(default='', max_length=200)),
                ('sdt', models.CharField(default='', max_length=100)),
                ('tongtien', models.IntegerField()),
                ('makh', models.ForeignKey(db_column='makh', on_delete=django.db.models.deletion.CASCADE, to='customer.khachhang')),
            ],
            options={
                'db_table': 'don_hang',
            },
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('mactdh', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dongia', models.IntegerField()),
                ('thanhtien', models.IntegerField()),
                ('soluong', models.IntegerField(default=1)),
                ('madh', models.ForeignKey(db_column='madh', on_delete=django.db.models.deletion.CASCADE, to='order.donhang')),
                ('masp', models.ForeignKey(db_column='masp', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'chi_tiet_don_hang',
            },
        ),
    ]
